
ARG BASE="ubuntu:20.04"
FROM $BASE
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y \
    && apt-get install -y vim git iproute2 wget curl python3-pip pkg-config libboost-all-dev libudev-dev nasm yasm liblz4-dev libsqlite3-dev zlib1g-dev \
        $(apt-cache search "linux-headers-5.15.*-generic" | tail -n 1 | awk '{print $1}') \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /tmp/requirements.txt \
    && rm /tmp/requirements.txt
